version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    target-branch: main
    labels:
      - dependabot
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
