name: 'Push to branch'

on:
  push:
    branches-ignore:
      - main
permissions: {}

concurrency:
  group: push-to-branch-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  secrets-scan:
    name: secrets-scan
    runs-on: ubuntu-latest
    steps:
      - name: Run secrets scan
        uses: ./security/secrets-scan
