name: 'Push to branch'

on:
  push:
    branches-ignore:
      - main
permissions: {}

jobs:
  secrets-scan:
    name: secrets-scan
    runs-on: ubuntu-latest
    concurrency:
      group: secrets-scan-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Run secrets scan
        uses: rusty-apps/github-actions/security/secrets-scan@c88aef61780b52030f39eb6d73fd44edd5ad0c8a
